// <auto-generated />
using System;
using JobVacancy.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobVacancy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113002557_ConfiguredVacancySkill")]
    partial class ConfiguredVacancySkill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobVacancy.API.models.entities.AreaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AreaEntities");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.Base.CommentBaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Depth")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.BasePostTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<short?>("ReadingTimeMinutes")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PostsBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EmployeeEnterpriseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("ContractLegalType")
                        .HasColumnType("integer");

                    b.Property<string>("ContractLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteSenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("integer");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalaryRange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("SalaryValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("InviteSenderId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeEnterprises");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EmployeeInvitationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<string>("EnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("InvitationLink")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("InviteSenderId")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProposedEndDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("ProposedStartDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("SalaryRange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("InviteSenderId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeInvitations", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EnterpriseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebSiteUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EnterpriseIndustryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndustryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("IsPrimary");

                    b.ToTable("EnterpriseIndustries");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.FavoriteCommentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CommentBaseEntityId")
                        .HasColumnType("text");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentBaseEntityId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique();

                    b.ToTable("FavoriteCommentEntities");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.FavoritePostEnterpriseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostEnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PostEnterpriseId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PostEnterpriseId")
                        .IsUnique();

                    b.ToTable("FavoritePostEnterprise", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.FavoritePostUserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<short?>("UserRating")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.HasIndex("PostUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PostUserId")
                        .IsUnique();

                    b.ToTable("FavoritePostUser", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.IndicationUserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndorsedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndorserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SkillRating")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndorsedId");

                    b.HasIndex("EndorserId", "EndorsedId")
                        .IsUnique();

                    b.ToTable("IndicationUser", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.IndustryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PositionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Describe")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.ReviewEnterpriseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("RatingCompensation")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("RatingCulture")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("RatingManagement")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("RatingOverall")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("RatingWorkLifeBalance")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.HasIndex("EnterpriseId", "UserId")
                        .IsUnique();

                    b.ToTable("review_enterprise", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.RoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("app_roles", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.SkillEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.UserSkillEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCertificateUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("UserSkill");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.VacancyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApplicationDeadLine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Benefits")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int?>("EducationLevel")
                        .HasColumnType("integer");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<string>("EnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastApplication")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Opening")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("Requirements")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("Responsibilities")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("numeric");

                    b.Property<short?>("Seniority")
                        .HasColumnType("SMALLINT");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkplaceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Vacancies", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.VacancySkillEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VacancyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Weight")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("YearsOfExperienceRequired")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("VacancyId", "SkillId")
                        .IsUnique();

                    b.ToTable("VacancySkills", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("app_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("app_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("app_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("app_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("app_user_tokens", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.CommentPostEnterpriseEntity", b =>
                {
                    b.HasBaseType("JobVacancy.API.models.entities.Base.CommentBaseEntity");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("PostId");

                    b.ToTable("CommentPostEnterprise", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.CommentPostUserEntity", b =>
                {
                    b.HasBaseType("JobVacancy.API.models.entities.Base.CommentBaseEntity");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("PostId");

                    b.ToTable("CommentPostUser", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PostEnterpriseEntity", b =>
                {
                    b.HasBaseType("JobVacancy.API.models.entities.BasePostTable");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnterpriseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("PostEnterprises", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PostUserEntity", b =>
                {
                    b.HasBaseType("JobVacancy.API.models.entities.BasePostTable");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("PostUsers", (string)null);
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.Base.CommentBaseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.Base.CommentBaseEntity", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EmployeeEnterpriseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.EnterpriseEntity", "Enterprise")
                        .WithMany("EmployeeEnterprise")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "InviteSender")
                        .WithMany("InvitationsEnterprise")
                        .HasForeignKey("InviteSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.PositionEntity", "Position")
                        .WithMany("EmployeeEnterprise")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("Employee")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("InviteSender");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EmployeeInvitationEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.EnterpriseEntity", "Enterprise")
                        .WithMany("EmployeeInvitations")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "InviteSender")
                        .WithMany("InvitationsSent")
                        .HasForeignKey("InviteSenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobVacancy.API.models.entities.PositionEntity", "Position")
                        .WithMany("EmployeeInvitations")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("InvitationsReceived")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("InviteSender");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EnterpriseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithOne("Enterprise")
                        .HasForeignKey("JobVacancy.API.models.entities.EnterpriseEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EnterpriseIndustryEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.EnterpriseEntity", "Enterprise")
                        .WithMany("IndustryLinks")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.IndustryEntity", "Industry")
                        .WithMany("EnterpriseLinks")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.FavoriteCommentEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.Base.CommentBaseEntity", null)
                        .WithMany("FavoriteCommentEntities")
                        .HasForeignKey("CommentBaseEntityId");

                    b.HasOne("JobVacancy.API.models.entities.Base.CommentBaseEntity", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.FavoritePostEnterpriseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.PostEnterpriseEntity", "PostEnterprise")
                        .WithMany("FavoritePostsEnterprise")
                        .HasForeignKey("PostEnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("FavoritePostsEnterprise")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostEnterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.FavoritePostUserEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.PostUserEntity", "PostUser")
                        .WithMany("FavoritePosts")
                        .HasForeignKey("PostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("FavoritePosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.IndicationUserEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "Endorsed")
                        .WithMany("ReceivedEndors")
                        .HasForeignKey("EndorsedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "Endorser")
                        .WithMany("SentEndors")
                        .HasForeignKey("EndorserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endorsed");

                    b.Navigation("Endorser");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.ReviewEnterpriseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.EnterpriseEntity", "Enterprise")
                        .WithMany("Reviews")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.PositionEntity", "Position")
                        .WithMany("Reviews")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.UserSkillEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.SkillEntity", "Skill")
                        .WithMany("UserSkill")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("UserSkill")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.VacancyEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.AreaEntity", "Area")
                        .WithMany("Vacancies")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.EnterpriseEntity", "Enterprise")
                        .WithMany("Vacancies")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.VacancySkillEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.SkillEntity", "Skill")
                        .WithMany("VacancySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.VacancyEntity", "Vacancy")
                        .WithMany("VacancySkills")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.CommentPostEnterpriseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.Base.CommentBaseEntity", null)
                        .WithOne()
                        .HasForeignKey("JobVacancy.API.models.entities.CommentPostEnterpriseEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.PostEnterpriseEntity", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.CommentPostUserEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.Base.CommentBaseEntity", null)
                        .WithOne()
                        .HasForeignKey("JobVacancy.API.models.entities.CommentPostUserEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.PostUserEntity", "Post")
                        .WithMany("CommentPostUser")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PostEnterpriseEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.CategoryEntity", "Category")
                        .WithMany("PostsEnterprise")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.EnterpriseEntity", "Enterprise")
                        .WithMany("Posts")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.BasePostTable", null)
                        .WithOne()
                        .HasForeignKey("JobVacancy.API.models.entities.PostEnterpriseEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PostUserEntity", b =>
                {
                    b.HasOne("JobVacancy.API.models.entities.CategoryEntity", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.BasePostTable", null)
                        .WithOne()
                        .HasForeignKey("JobVacancy.API.models.entities.PostUserEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobVacancy.API.models.entities.UserEntity", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.AreaEntity", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.Base.CommentBaseEntity", b =>
                {
                    b.Navigation("FavoriteCommentEntities");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.CategoryEntity", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("PostsEnterprise");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.EnterpriseEntity", b =>
                {
                    b.Navigation("EmployeeEnterprise");

                    b.Navigation("EmployeeInvitations");

                    b.Navigation("IndustryLinks");

                    b.Navigation("Posts");

                    b.Navigation("Reviews");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.IndustryEntity", b =>
                {
                    b.Navigation("EnterpriseLinks");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PositionEntity", b =>
                {
                    b.Navigation("EmployeeEnterprise");

                    b.Navigation("EmployeeInvitations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.SkillEntity", b =>
                {
                    b.Navigation("UserSkill");

                    b.Navigation("VacancySkills");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.UserEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Employee");

                    b.Navigation("Enterprise");

                    b.Navigation("FavoritePosts");

                    b.Navigation("FavoritePostsEnterprise");

                    b.Navigation("InvitationsEnterprise");

                    b.Navigation("InvitationsReceived");

                    b.Navigation("InvitationsSent");

                    b.Navigation("Posts");

                    b.Navigation("ReceivedEndors");

                    b.Navigation("Reviews");

                    b.Navigation("SentEndors");

                    b.Navigation("UserSkill");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.VacancyEntity", b =>
                {
                    b.Navigation("VacancySkills");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PostEnterpriseEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavoritePostsEnterprise");
                });

            modelBuilder.Entity("JobVacancy.API.models.entities.PostUserEntity", b =>
                {
                    b.Navigation("CommentPostUser");

                    b.Navigation("FavoritePosts");
                });
#pragma warning restore 612, 618
        }
    }
}
