apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: "postgres-headless"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      resources:
        limits:
          memory: "1524Mi"
          cpu: "500m"
        requests:
          memory: "512Mi"
          cpu: "100m"
      
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "job_vacancy"
            - name: POSTGRES_USER
              value: "adm"
            - name: POSTGRES_PASSWORD
              value: "437563894566237465"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql 
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path